#!/bin/bash


super + {_,shift + }v
	bspc node '@parent' -R {_,-}90
# wm independent hotkeys
super + ctrl + {j, k}
    bspc node -f {next, prev}.local

# terminal emulator
super + Return
          alacritty 
  	    # alacritty

# vscode emulator
super + shift + t
		code
#chrome
super + shift + c
		google-chrome-stable
#firefox
super + shift + f
		firefox
# telegram
# super + t
# 	telegram-desktop
#Discord
shift + alt + d
	discord
super + shift + u
		reboot
super + shift + i
	 	shutdown now	
# program launcher
super + @space
	~/.config/rofi/scripts/./launcher_t5
#greenclip 
alt + v
	~/bin/clipboard/greenclip

#lockscreen
alt + x
	betterlockscreen -l
#audio player
shift + alt + p 
        ~/bin/blt-connect

# make sxhkd reload its configuration files:
super + Escape
 	pkill -USR1 -x sxhkd && notify-send "sxhkdrc reloaded"
#file manager
super + n 
        nemo 
# bspwm hotkeys

super + e : {h,j,k,l}
    bspwm_resize expand {west,south,north,east} 50

super + shift + e : {h,j,k,l}
    bspwm_resize contract {west,south,north,east} 50
# quit/restart bspwm
super + shift + {q,r}
	bspc {quit,wm -r}

# close and kill
super + {_,shift + }q
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

super + m
	bspc desktop -l next && polyhide
# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest window
        # nsxiv ~/.local/src/wals
# 	bspc node -s biggest.window

#
# state/flags
#

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#
# focus the node in the given direction
super + {_,alt+ }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,r,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous window in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local.!hidden.window

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

#Brightness
XF86MonBrightnessUp
	brightnessctl set +5%
XF86MonBrightnessDown
	brightnessctl set 5%-
super + F4
	brightnessctl set 5%-

# Volume
# Decrease volume
XF86AudioLowerVolume
  pamixer --decrease 5
# Increase volume
XF86AudioRaiseVolume
  pamixer --increase 5
# Mute volume
XF86AudioMute
  pamixer --toggle-mute


#
# preselect
#
super + b
	bspc wm -r
# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
# expand a window by moving one of its side outward
#
super + shift + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}



#	light -U 3
#gaps
# super + shift + +
#     bspc config window_gap +5
#
#
Print
 maim | tee ~/images/ss/$(date +%s).png | xclip -selection clipboard -t image/png
