#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xcompmgr &
feh --bg-fill ~/wallpaper/wp6.jpg &
xrandr --output eDP-1 --mode 1600x900 &
dunst &
greenclip daemon &
./.config/polybar/launch.sh

bspc monitor -d I II III IV V

bspc config normal_border_color "#4c566a"
bspc config focused_border_color "#b7bdf8"
bspc config border_width         2.5
bspc config window_gap           24
bspc config split_ratio          0.52
bspc config borderless_monocle   false 
bspc config gapless_monocle      false 

bspc config bottom_padding 0
bspc config top_padding 29
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Telegram-desktop state=pseudo_tiled
bspc rule -a Nsxiv state=floating
bspc rule -a Zathura state=tiled

bspc config focus_follows_pointer true
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

#touchpad gestures
libinput-gestures-setup stop desktop autostart start &

# Remove x cursor
xsetroot -cursor_name left_ptr &
#hhpc -i 5 &

#Polybar Launching
~/.config/polybar/./launch.sh

# ~/.config/polybar/lowsmall/./launch.sh
# ~/lowsmall/./launch.sh

# ~/.config/polybar/low/./launch.sh

#enable touchpad tapping and natural scrolling
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
# bspc config gapless_monocle false
